/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package starwars

import io.ktor.application.call
import io.ktor.http.ContentType
import io.ktor.response.respondText
import io.ktor.routing.get
import io.ktor.routing.routing
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(App().greeting)

    embeddedServer(Netty, 8080) {
        routing {
            get("/") {
                call.respondText("Starwars", ContentType.Text.Html)
            }
        }
    }.start(wait = true)
}
